version: "3.5"

services:
  notebooks:
    build: notebooks
    env_file:
      - .env
    volumes:
      - ./research:/mnt/code
      - ${DATA_VOLUME}:/mnt/data
    ports:
      - 8888:8888
    image: light-ds-notebooks
    container_name: light-ds-notebooks

  code:
    build: code
    env_file:
      - .env
    volumes:
      - ./code:/mnt/code
      - ${DATA_VOLUME}:/mnt/data
    image: light-ds-code
    container_name: light-ds-code
