# Jupyter pyspark image from https://hub.docker.com/r/datasciencebrigade/ubuntu-python3
FROM datasciencebrigade/ubuntu-python3:1.0


COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
