version: "3.5"

services:
  research:
    build:
        context: research
        args:
          JUPYTER_EXTERNAL_PORT: ${JUPYTER_EXTERNAL_PORT}
    volumes:
      - ./research:/mnt/code
      - ${DATA_VOLUME}:/mnt/data
    environment:
      TIMEZONE: America/Sao_Paulo
    ports:
      - ${JUPYTER_EXTERNAL_PORT}:${JUPYTER_EXTERNAL_PORT}
    image: nomeprojeto-research
    container_name: nomeprojeto-research-${CONTAINER_TAG}

  processing-test:
    build: processing
    env_file:
      - .env
    environment:
      TIMEZONE: America/Sao_Paulo
    ports:
      - ${USER_PORT_TAG}5000:5000
    volumes:
      - ./processing:/mnt/code
      - ${DATA_VOLUME}:/mnt/data
    image: nomeapi-processing-test
    container_name: nomeapi-processing-test-${CONTAINER_TAG}
